Task 1. Pytorch Basics

Propose a PyTorch nn.Module that functions as a power equation: 

$y=x^n$

Where x is a vector of positive values and parameter n should be learnable and constrained to values in the range [1, 3]. The outputs from the nn.Module forward method should always be positive. 

In [956]:
import torch
import torch.nn as nn
import sys

class LimitedPowah(nn.Module):
    def __init__(self, eps = 1e-8, maxint = sys.maxsize):
        super(LimitedPowah, self).__init__()
        self.eps = eps
        #As parameters should be constrained to range [1, 3], I can`t use torch.rand, as it works in the range [0,1)
        self.learnable_param = nn.Parameter(1+2*(torch.randint(size=(1,), low = 0, high = maxint)/maxint))

    def forward(self, x):
        
        x = torch.clamp(input=x, min = self.eps)
        #Ensuring that outputs are always positive
        out = torch.pow(x,self.learnable_param)
        return out
    

    #In case parameters should ALWAYS be constrained to range [1,3], here is code, which technically works
    #I`m almost sure that I'm just overthinking, and it's just a bunch of cursed code
    '''def clamp_parameters(self):
        with torch.no_grad():
            self.learnable_param.data.clamp_(1, 3)

            
    def parameters(self, recurse=True):
        self.clamp_parameters()  
        return super(LimitedPowah, self).parameters(recurse)
    
    def backward(self, loss):
        loss.backward(retain_graph=True)'''


Prepare a Jupyter notebook to demonstrate the use of this nn.Module on a random valued batched vector (torch.tensor) with dimensions 8x16. In our case, 8 is a batch length and 16 is a length of the vector x.

In [1027]:
powah_module = LimitedPowah()
for param in powah_module.parameters():
    print(type(param), param.size(), param)

#batched_vector = torch.zeros((8,16))
#In case torch.rand returned 0
batched_vector = torch.clamp(torch.rand((8,16)), min=1e-16)*1000

y = powah_module(batched_vector)
print(y)

<class 'torch.nn.parameter.Parameter'> torch.Size([1]) Parameter containing:
tensor([2.3111], requires_grad=True)
tensor([[2.1405e+06, 1.3807e+06, 2.8691e+06, 1.3142e+06, 1.5979e+06, 6.8320e+06,
         6.8564e+06, 1.7235e+05, 2.3583e+06, 1.5363e+05, 2.3992e+05, 3.5563e+06,
         5.9958e+05, 3.6427e+06, 6.3846e+06, 7.0400e+06],
        [1.4862e+05, 6.8089e+06, 3.3968e+05, 4.6003e+06, 1.6237e+06, 3.1180e+04,
         7.7086e+06, 6.8642e+06, 4.2108e+04, 4.7643e+06, 7.1799e+06, 4.2327e+06,
         9.3962e+05, 1.2421e+05, 3.5435e+06, 4.8426e+06],
        [8.7937e+05, 3.3704e+05, 5.7563e+06, 1.2940e+04, 1.7501e+06, 2.5153e+06,
         2.0497e+06, 3.9358e+05, 3.2814e+06, 1.1499e+05, 3.4409e+06, 5.1876e+05,
         4.3719e+05, 2.9432e+05, 1.1694e+06, 7.9489e+05],
        [1.4506e+06, 2.5858e+06, 9.0323e+04, 1.3978e+06, 1.5097e+06, 1.0409e+06,
         4.0896e+06, 6.5904e+04, 5.1552e+05, 5.2908e+06, 3.1487e+06, 5.1563e+06,
         5.0784e+06, 3.1559e+06, 6.1031e+05, 4.6518e+05],
      

Cursed testings

In [955]:
'''import torch.optim as optim
powah_module_cursed = LimitedPowah()
for param in powah_module_cursed.parameters():
    print(type(param), param.size(), param)
optimizer = optim.SGD(powah_module_cursed.parameters(), lr=1)

input = torch.tensor(2.0)
target = torch.tensor(1000.0)

output = powah_module_cursed(input)

loss = (output - target).pow(2)

optimizer.zero_grad()
loss.backward()
optimizer.step()

for param in powah_module_cursed.parameters():
    print(type(param), param.size(), param)'''

<class 'torch.nn.parameter.Parameter'> torch.Size([1]) Parameter containing:
tensor([1.3818], requires_grad=True)
<class 'torch.nn.parameter.Parameter'> torch.Size([1]) Parameter containing:
tensor([3.], requires_grad=True)
